name: Laravel CI

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'

    - name: Install Dependencies
      run: composer install --ignore-platform-reqs

    - name: FTP Upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.foliageschool.com
        username: demo-ci-cd@demo.cicd.phpteam.in
        password: A2}g)x0a[pYu
        server-dir: ./demo.cicd.phpteam.in/
